const IG_SPOTS = {
  "Tokyo, Japan": ["📸 Shibuya Crossing at night", "📸 Meguro River cherry blossoms", "📸 Senso-ji Temple gates", "📸 Omoide Yokocho", "📸 TeamLab Planets water area", "📸 Kaminarimon Gate lantern", "📸 Harajuku Takeshita Street", "📸 Shinjuku Golden Gai alleys", "📸 Tokyo Skytree observation deck", "📸 Meiji Jingu sake barrels", "📸 Akihabara neon streets", "📸 Odaiba Gundam statue", "📸 Roppongi Hills Mori Tower", "📸 Ueno Park pagoda", "📸 Tokyo Tower from Zojoji Temple"],
  "Paris, France": ["📸 Trocadéro sunrise", "📸 Louvre Pyramids at dusk", "📸 Montmartre's Maison Rose", "📸 Palais Royal striped columns", "📸 Moulin Rouge windmill", "📸 Sainte-Chapelle stained glass", "📸 Arc de Triomphe rooftop view", "📸 Montparnasse Tower sunset", "📸 Pont Alexandre III bridge", "📸 Luxembourg Gardens Palace", "📸 Shakespeare and Company bookstore", "📸 Notre-Dame facade", "📸 Pantheon dome", "📸 Sacré-Cœur steps", "📸 Saint-Germain-des-Prés cafes"],
  "New York, USA": ["📸 DUMBO Washington Street", "📸 Central Park Bow Bridge", "📸 The Vessel", "📸 High Line at sunset", "📸 Times Square neon lights", "📸 Top of the Rock observation deck", "📸 Flatiron Building", "📸 Brooklyn Bridge sunrise walk", "📸 Grand Central Terminal clock", "📸 Oculus transportation hub", "📸 Washington Square Park arch", "📸 Chelsea Market halls", "📸 Statue of Liberty from ferry", "📸 Greenwich Village brownstones", "📸 Empire State Building view"],
  "Bangkok, Thailand": ["📸 Wat Arun at sunset", "📸 Mahanakhon SkyWalk glass floor", "📸 Asiatique The Riverfront", "📸 Grand Palace golden stupas", "📸 Wat Pho reclining Buddha", "📸 Erawan Museum pink elephant", "📸 Chocolate Ville pastel houses", "📸 Chatuchak Market colorful stalls", "📸 Lumpini Park monitor lizards", "📸 Yaowarat Road Chinatown neon", "📸 Khaosan Road street food", "📸 Jim Thompson House silk", "📸 Maeklong Railway Market train", "📸 Floating Market boats", "📸 Wat Paknam green glass"] ,
  "Dubai, UAE": ["📸 Burj Khalifa summit", "📸 Dubai Miracle Garden hearts", "📸 Museum of the Future exterior", "📸 Dubai Frame glass walk", "📸 Palm Jumeirah monorail view", "📸 Burj Al Arab from Madinat Jumeirah", "📸 Global Village pavilions", "📸 Dubai Mall aquarium", "📸 Desert Safari sunset dunes", "📸 Al Fahidi historical neighborhood", "📸 Dubai Marina walk yachts", "📸 Gold Souk brilliant windows", "📸 La Mer beach huts", "📸 Bluewaters Island Ain Dubai", "📸 Atlantis fountains"],
  "London, UK": ["📸 Tower Bridge view", "📸 Notting Hill colorful doors", "📸 Sketch London pink room", "📸 Big Ben from Westminster", "📸 London Eye capsules", "📸 British Museum Great Court", "📸 St Paul's Cathedral dome", "📸 Covent Garden market", "📸 Piccadilly Circus screens", "📸 Columbia Road Flower Market", "📸 Shoreditch street art", "📸 Leadenhall Market", "📸 Primrose Hill city skyline", "📸 Natural History Museum Hintze Hall", "📸 Greenwich Observatory"],
  "Singapore": ["📸 Gardens by the Bay Supertree Grove", "📸 Jewel Changi Rain Vortex", "📸 Marina Bay Sands infinity pool", "📸 ArtScience Museum lotus", "📸 Haji Lane colorful murals", "📸 Merlion Park statue", "📸 Clarke Quay colorful riverside", "📸 Old Hill Street Police Station windows", "📸 Chinatown Buddha Tooth Relic Temple", "📸 Sentosa Palawan Beach suspension bridge", "📸 Universal Studios globe", "📸 Botanic Gardens Swan Lake", "📸 National Gallery aluminum canopy", "📸 Little India Sri Veeramakaliamman Temple", "📸 Henderson Waves bridge"],
  "Sydney, Australia": ["📸 Bondi Icebergs pool", "📸 Sydney Opera House sails", "📸 Mrs Macquarie's Chair sunset", "📸 Sydney Harbour Bridge climb", "📸 Luna Park entrance face", "📸 The Rocks cobblestone lanes", "📸 Taronga Zoo harbour view", "📸 QVB romanesque architecture", "📸 Darling Harbour ferris wheel", "📸 Royal Botanic Garden flowers", "📸 Barangaroo Reserve parklands", "📸 Bondi to Coogee coastal walk", "📸 Manly Beach pine trees", "📸 Watsons Bay Hornby Lighthouse", "📸 Circular Quay ferries"],
  "Rome, Italy": ["📸 Trevi Fountain early morning", "📸 Colosseum interior", "📸 Spanish Steps sunset", "📸 Pantheon oculus", "📸 Roman Forum ruins from Capitoline Hill", "📸 Vatican St. Peter's Basilica dome", "📸 Sistine Chapel exterior courtyard", "📸 Piazza Navona fountains", "📸 Castel Sant'Angelo bridge angels", "📸 Trastevere ivy-draped alleys", "📸 Villa Borghese gardens lake", "📸 Monument to Victor Emmanuel II terrace", "📸 Orange Garden keyhole view", "📸 Campo de' Fiori market stalls", "📸 Mouth of Truth"],
  "Bali, Indonesia": ["📸 Lempuyang Temple Gates of Heaven", "📸 Tegallalang Rice Terrace swing", "📸 Nusa Penida T-Rex cliff (Kelingking)", "📸 Uluwatu Temple monkey forest", "📸 Tanah Lot ocean temple sunset", "📸 Campuhan Ridge Walk morning", "📸 Ulun Danu Beratan water temple", "📸 Tirta Gangga water palace koi fish", "📸 Banyumala Twin Waterfalls", "📸 Monkey Forest Ubud stone carvings", "📸 Diamond Beach Nusa Penida stairs", "📸 Seminyak beach bean bags sunset", "📸 Handara Golf Course iconic gates", "📸 Tukad Cepung cave waterfall", "📸 Mount Batur sunrise hike"],
  "Cairo, Egypt": ["📸 Great Sphinx with Pyramids", "📸 Khan el-Khalili lanterns", "📸 Cairo Citadel view", "📸 Al-Azhar Mosque courtyard", "📸 Egyptian Museum golden mask", "📸 Nile River felucca ride at sunset", "📸 Cairo Tower city panorama", "📸 Hanging Church in Coptic Cairo", "📸 Mosque of Muhammad Ali alabaster domes", "📸 Saqqara Step Pyramid", "📸 Memphis Ramses II statue", "📸 Al-Muizz Street Islamic architecture", "📸 Bab Zuweila minaret climb view", "📸 Saladin Citadel ancient walls", "📸 Giza plateau camel ride silhouette"],
  "Toronto, Canada": ["📸 Nathan Phillips Square sign", "📸 CN Tower glass floor", "📸 Distillery District lights", "📸 ROM Michael Lee-Chin Crystal", "📸 Gooderham Building flatiron", "📸 Graffiti Alley colors", "📸 Ripley's Aquarium shark tunnel", "📸 Casa Loma gothic exterior", "📸 Toronto Islands skyline view", "📸 Kensington Market vintage storefronts", "📸 St. Lawrence Market interior", "📸 High Park cherry blossoms (spring)", "📸 Aga Khan Museum pools", "📸 Yonge-Dundas Square neons", "📸 Sugar Beach pink umbrellas"],
  "Istanbul, Turkey": ["📸 Hagia Sophia interior mosaics", "📸 Galata Tower view from street", "📸 Grand Bazaar spice aisles", "📸 Blue Mosque courtyards", "📸 Bosphorus Bridge at night", "📸 Topkapi Palace harem tiles", "📸 Basilica Cistern Medusa heads", "📸 Dolmabahce Palace gates", "📸 Ortakoy Mosque with bridge backdrop", "📸 Balat colorful houses rows", "📸 Istiklal Avenue red tram", "📸 Suleymaniye Mosque courtyard", "📸 Maiden's Tower at sunset", "📸 Camlica Hill panoramic view", "📸 Egyptian Spice Bazaar sweet towers"],
  "Amsterdam, Netherlands": ["📸 Keizersgracht canal bridge", "📸 Zaanse Schans windmills", "📸 Damrak gingerbread houses", "📸 Rijksmuseum passage", "📸 Vondelpark ponds", "📸 Anne Frank House exterior", "📸 Jordaan neighborhood bikes", "📸 Bloemenmarkt floating flower market", "📸 Magere Brug skinny bridge at night", "📸 A'DAM Lookout swings", "📸 NDSM Wharf street art", "📸 Heineken Experience copper tanks", "📸 Westerkerk church tower", "📸 Nine Streets boutique windows", "📸 Begijnhof hidden courtyard"],
  "Seoul, South Korea": ["📸 Bukchon Hanok Village alleys", "📸 N Seoul Tower locks of love", "📸 Starfield Library in COEX", "📸 Gyeongbokgung Palace in Hanbok", "📸 Dongdaemun Design Plaza curves", "📸 Cheonggyecheon Stream lantern lights", "📸 Myeongdong neon street food", "📸 Nami Island tree-lined paths", "📸 Lotte World Magic Island castle", "📸 Ihwa Mural Village wings", "📸 Jogyesa Temple lotus lanterns", "📸 Changdeokgung Secret Garden", "📸 Banpo Bridge Rainbow Fountain", "📸 Hongdae vibrant indie streets", "📸 Gangnam statue of hands"],
  "Cape Town, South Africa": ["📸 Bo-Kaap colorful houses", "📸 Table Mountain cable car view", "📸 Camps Bay beach rocks and apostles", "📸 Boulders Beach penguins", "📸 Cape of Good Hope sign", "📸 V&A Waterfront ferris wheel", "📸 Kirstenbosch Botanical Garden canopy walkway", "📸 Chapman's Peak Drive coastal curves", "📸 Muizenberg Beach colorful huts", "📸 Lion's Head sunrise hike", "📸 Robben Island Mandela's cell", "📸 Signal Hill paragliding launch", "📸 Zeitz MOCAA museum silo architecture", "📸 Cape Winelands Stellenbosch vineyards", "📸 Hout Bay seal snorkeling"],
  "New Delhi, India": ["📸 Humayun's Tomb symmetry", "📸 Jama Masjid minaret view", "📸 India Gate at night", "📸 Lotus Temple petals", "📸 Red Fort Lahori Gate", "📸 Qutub Minar soaring tower", "📸 Akshardham Temple intricate carvings", "📸 Chandni Chowk bustling rickshaws", "📸 Agrasen ki Baoli stepwell", "📸 Lodhi Gardens ancient tombs", "📸 Safdarjung Tomb gardens", "📸 Rashtrapati Bhavan facade", "📸 Gurudwara Bangla Sahib reflecting pool", "📸 Dilli Haat colorful handicrafts", "📸 Hauz Khas Village ruins and lake"],
  "Kuala Lumpur, Malaysia": ["📸 Petronas Twin Towers from KLCC Park", "📸 Batu Caves rainbow steps", "📸 Thean Hou Temple red lanterns", "📸 KL Tower sky deck", "📸 Sultan Abdul Samad Building Moorish architecture", "📸 Merdeka 118 mega-tall skyscraper", "📸 Jalan Alor street food hustle", "📸 Sri Mahamariamman Temple gopuram", "📸 Perdana Botanical Gardens canopy", "📸 Islamic Arts Museum blue domes", "📸 Changkat Bukit Bintang nightlife neon", "📸 Saloma Link bridge illuminated", "📸 RexKL bookstore labyrinth", "📸 Putrajaya Pink Mosque", "📸 Central Market heritage facade"],
  "Reykjavik, Iceland": ["📸 Blue Lagoon geothermal waters", "📸 Hallgrimskirkja church architecture", "📸 Sun Voyager sculpture", "📸 Harpa Concert Hall glass facade", "📸 Rainbow Street leading to church", "📸 Tjornin lake and colourful houses", "📸 Perlan museum glass dome", "📸 Grotta Lighthouse northern lights", "📸 Old Harbour fishing boats", "📸 Laugavegur street art", "📸 Thingvellir National Park tectonic plates", "📸 Gullfoss waterfall spray", "📸 Geysir erupting", "📸 Seljalandsfoss behind the waterfall", "📸 Skogafoss massive drop"],
  "Buenos Aires, Argentina": ["📸 Caminito colorful street in La Boca", "📸 El Ateneo Grand Splendid bookshop", "📸 Puerto Madero Woman's Bridge", "📸 Obelisco de Buenos Aires", "📸 Casa Rosada pink palace", "📸 Recoleta Cemetery elaborate mausoleums", "📸 San Telmo market antiques", "📸 Plaza de Mayo historic square", "📸 Teatro Colon grand interior", "📸 Floralis Genérica metal flower", "📸 Palacio Barolo lighthouse view", "📸 Palermo Soho street art", "📸 Mafalda statue in San Telmo", "📸 Japanese Garden red bridge", "📸 La Bombonera stadium murals"]
};

export function buildItinerary(destObj, numDays, style){
  const pool=destObj.activities[style==="packed"?"packed":"relaxed"]||destObj.activities.relaxed;
  const allActivities=[...pool];
  if(style==="packed"&&destObj.activities.packed){
    const extra=destObj.activities.relaxed.filter(a=>!allActivities.includes(a));
    allActivities.push(...extra);
  }
  const themes=[
    {title:"Arrival & First Impressions"},{title:"Deep Dive"},{title:"Local Life"},
    {title:"Hidden Gems"},{title:"Culture & Cuisine"},{title:"Adventure Day"},
    {title:"Slow Morning"},{title:"Neighbourhood Wander"},{title:"Nature & Outdoors"},{title:"Final Day"},
  ];
  const timeTags=style==="packed"
    ?["Morning: 8am start","Afternoon: full schedule","Evening: dinner + bar"]
    :["Morning: leisurely start","Afternoon: one main thing","Evening: your choice"];

  let actIdx=0;
  return Array.from({length:numDays},(_,i)=>{
    const theme=themes[Math.min(i,themes.length-1)];
    const actsPerDay=style==="packed"?3:2;
    const acts=[];
    let dayBudgetBase = destObj.rate > 0.05 ? 120 : (destObj.rate > 0.01 ? 80 : 50); // rough base USD mapping
    if(style==="packed") dayBudgetBase *= 1.3;
    const randomizedBudget = Math.floor(dayBudgetBase * (0.8 + Math.random() * 0.4));
    let budgetStr = `~$${randomizedBudget} USD`;
    for(let a=0;a<actsPerDay;a++){
      if(actIdx<allActivities.length) acts.push(allActivities[actIdx++]);
    }
    if(acts.length===0) acts.push("Free exploration & local dining");
    
    // Inject an IG Spot for the day
    const spots = IG_SPOTS[destObj.name] || ["📸 Beautiful central architecture", "📸 Scenic local cafe", "📸 Sunset panorama point"];
    const spot = spots[i];
    if(spot) acts.push(`Instagram Spot: ${spot}`);
    return{day:i+1,title:theme.title,activities:acts,tags:timeTags.slice(0,style==="packed"?3:2),budgetStr};
  });
}
